apiVersion: v2
name: xpos
description: A Helm chart for XPOS POS System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - xpos
  - pos
  - laravel
maintainers:
  - name: XPOS Team

dependencies:
  - name: redis
    version: "24.0.7"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
