{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xpos.fullname" . }}-secrets
  labels:
    {{- include "xpos.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.secrets.appKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  {{- if or .Values.redis.enabled .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | default "" | quote }}
  {{- end }}
{{- end }}
